// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMf5S8gh6J_oB8ZO0VvP-lE4XVz-q5d9I',
    appId: '1:125685045533:web:f88a8720d245a1381469f4',
    messagingSenderId: '125685045533',
    projectId: 'tiger-vs-goats',
    authDomain: 'tiger-vs-goats.firebaseapp.com',
    storageBucket: 'tiger-vs-goats.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQInLLVQsfv7DDBQkCd4mE9gD_aF9BKM',
    appId: '1:125685045533:android:77bd709c13c784671469f4',
    messagingSenderId: '125685045533',
    projectId: 'tiger-vs-goats',
    storageBucket: 'tiger-vs-goats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNj-1k5-Bb8wpve6ArZQI27l-omr8ezQ',
    appId: '1:125685045533:ios:bd7f6433b5ad735f1469f4',
    messagingSenderId: '125685045533',
    projectId: 'tiger-vs-goats',
    storageBucket: 'tiger-vs-goats.firebasestorage.app',
    iosBundleId: 'com.example.tigerVsGoat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNj-1k5-Bb8wpve6ArZQI27l-omr8ezQ',
    appId: '1:125685045533:ios:bd7f6433b5ad735f1469f4',
    messagingSenderId: '125685045533',
    projectId: 'tiger-vs-goats',
    storageBucket: 'tiger-vs-goats.firebasestorage.app',
    iosBundleId: 'com.example.tigerVsGoat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMf5S8gh6J_oB8ZO0VvP-lE4XVz-q5d9I',
    appId: '1:125685045533:web:a991cc967fdbef571469f4',
    messagingSenderId: '125685045533',
    projectId: 'tiger-vs-goats',
    authDomain: 'tiger-vs-goats.firebaseapp.com',
    storageBucket: 'tiger-vs-goats.firebasestorage.app',
  );
}
